name: Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: xu-cheng/texlive-action@v2
        with:
          run: |
            apk add make
            make

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: '**/*.pdf'
          if-no-files-found: error

  push:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: pdf

      - name: Push
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: pdf
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
